Feed cannot be loaded
VolkovLabs/volkovlabs-rss-datasource pull request #61
Opened 2024-02-06 08:40 UTC by vitPinchuk

Resolves: [#60 ](https://github.com/VolkovLabs/volkovlabs-rss-datasource/issues/60)

2024-02-06 11:23 UTC, asimonok requested changes

2024-02-06 11:23 UTC, asimonok commented on src/api/api.ts
> +          Accept: 'application/rss+xml;charset=UTF-8',
Please remove charset from the header. Just `application/rss+xml`

2024-02-07 06:03 UTC, asimonok approved these changes
Looks good!

@mikhail-vl ready for review

2024-02-08 02:45 UTC, mikhail-vl commented on src/api/api.ts
> +          Accept: 'application/rss+xml',
Data Source supports RSS and Atom feedback. For Atom the Content-Type is `application/atom+xml`. With this change we may break it?

2024-02-08 02:51 UTC, mikhail-vl approved these changes
Looks good!

2024-02-08 02:56 UTC, merged